
development:
  adapter: postgresql
  encoding: unicode
  database: lean_development
  pool: 5
  username: postgres
  password: '123456'
  host: localhost
  port: 5433


test:
  adapter: postgresql
  encoding: unicode
  database: lean_test
  pool: 5
  username: postgres
  password: '123456'
  host: localhost
  port: 5433

production:
  adapter: postgresql
  encoding: unicode
  database: lean_production
  pool: 5
  username: postgres
  password: '123456'
  host: localhost
  port: 5433
