
development:
  adapter: postgresql
  encoding: unicode
  database: lean_development4
  pool: 5
  username: postgres
  password: '260489'
  host: localhost
  port: 5432


test:
  adapter: postgresql
  encoding: unicode
  database: lean_test
  pool: 5
  username: postgres
  password: '260489'
  host: localhost
  port: 5432

production:
  adapter: postgresql
  encoding: unicode
  database: lean_production
  pool: 5
  username: postgres
  password: '260489'
  host: localhost
  port: 5432
